# Generated by Django 3.0.6 on 2020-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/animal/'),
        ),
    ]
