# Generated by Django 3.0.6 on 2020-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='media/None/no_img.jpg', upload_to='media/animal/'),
        ),
    ]
