# Generated by Django 3.0.6 on 2020-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20200531_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/animal/'),
        ),
    ]
