# Generated by Django 3.0.6 on 2020-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20200531_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='animal/'),
        ),
    ]
